name: Rails CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo /etc/init.d/mysql start
      - name: Install bundle
        run: sudo gem install bundler:2.1.4
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
              ${{ runner.os }}-gems-
      - name: Install bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop
      - name: Rails Best Practices
        run: bundle exec rails_best_practices -e "db/schema.rb,db/migrate,vendor,app/models/application_record.rb"
      - name: Rspec        
        run: |
          NOREPLY_EXAMPLE=noreply@example.com DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=naitei_ruby_2020_airport_cv_management_test TEST_DATABASE_NAME=naitei_ruby_2020_airport_cv_management_test bundle exec rails db:create
          NOREPLY_EXAMPLE=noreply@example.com DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=naitei_ruby_2020_airport_cv_management_test TEST_DATABASE_NAME=naitei_ruby_2020_airport_cv_management_test bundle exec rspec --format documentation
